- name: Install pkgs via apt
  apt:
    pkg:
      - vim
      - python3
      - python3-dev
      - python3-pip
      - python3-venv
      - clang
      - libc++abi-dev
      - libc++-dev
  become: yes
- name: Install online-judge-tools
  pip:
    name: online-judge-tools
    extra_args: --user
