- name: Update and upgrade apt
  apt:
    update_cache: yes
    upgrade: "yes"
  become: yes
- name: Install pkgs via apt
  apt:
    pkg:
      - cmake
      - pkg-config
      - libfreetype6-dev
      - libfontconfig1-dev
      - libxcb-xfixes0-dev
      - binutils
      - build-essential
      - cmake
      - curl
      - default-jdk
      - fcitx-mozc
      - ffmpeg
      - file
      - gcc
      - gdb
      - ghex
      - git
      - gnome-getting-started-docs-ja
      - gnome-user-docs-ja
      - htop
      - inetutils-traceroute
      - libpq-dev
      - libssl-dev
      - ltrace
      - nasm
      - netcat
      - python-is-python3
      - python3
      - python3-dev
      - python3-pip
      - python3-venv
      - qemu
      - qemu-system-x86
      - ssh
      - strace
      - tmux
      - tree
      - ubuntu-restricted-extras
      - vim
      - wget
  become: yes
- name: Add git configuration
  git_config:
    name: "{{ item.name }}"
    scope: global
    value: "{{ item.value }}"
  with_items:
    - {name: "user.name",  value: "uta8a" }
    - {name: "user.email", value: "noumodulity@gmail.com" }
    - {name: "core.editor", value: "vim"}
- name: Create .cache
  file:
    path: "{{ ansible_env.HOME }}/.cache"
    state: directory
    mode: '0755'