name: Test dotfiles on GitHub Actions
on: [push]
jobs:
  test_ubuntu_20:
    name: Test for Ubuntu 20.04
    strategy:
      matrix:
        os: ['ubuntu-20.04']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Run test
        run: |
          /entry-point.sh